### PR TITLE
Ft design tear down

### PR DESCRIPTION
**Pull request by kbjude**
This Pull Request creates a grayscale heat map of the www.smashingmagazine.com homepage. 

The focus us to only highlight the visual design elements that capture the user's attention at a first glance.

Code has been validated for errors.

A descriptive readme file is included together with a screenshot of the main page.

Main technologies used are CSS3 and HTML5.

### CODE REVIEW

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Nice work team!
You have done a great job coming this far, please consider the following comments, give your project a second look and implement the appropriate changes.

#### Missing page sections
You've done a nice job with the first two sections on the page, the navigation, and the two-column section, however the rest of it is in a bit of chaos with some sections running into each other and some not existing at all. Please note that the essence of this project is to help us understand user experience, UI flows and positioning with CSS and as such, each section on the original page needs to be replicated as-is. I have gone ahead to include some screenshots of the issues that were found as well as a list of all expected sections just below this comment. Please give them a thorough look.
##### Required Sections
* Navigation bar 
It uses div and positions elements as at the source page

* 2 articles rows 
It contains 2 articles, each takes half of the width

* 3 articles rows
It contains 3 articles, each takes one-third of the width

* 1 article row
It contains 1 article, which takes full width

* Footer
It contains centered links (content is not important)

##### Screenshots
screenshot
screenshot
screenshot
screenshot
screenshot
screenshot
screenshot

#### Descriptive PR
You need a more descriptive PR as it is a hard requirement. Consider describing the work you have completed in the branch in as much detail as you can. Your PR is meant to describe your work strictly and add useful information for the reviewer, not really to describe the TSEs' job. Please consider the following [example](https://github.com/Oluwadamilareolusakin/show-junkie-api/pull/1)
screenshot

#### Live link
Please remember to update the live link in your project to point to the actual website. My go-to resource for making live links is [Raw Githack](https://raw.githack.com) Please check it out, it's free and easy to use :+1: 

#### Horizontal Scroll
You seem to have a little bug with one of the elements of the page, shooting out beyond the browser's maximum width. This may be as a result of a margin or padding you have set up. One of the easiest ways I have found to correct this issue is to set the default `box-sizing` property to `border-box` as follows `*{box-sizing: border-box}`. Please read some more about it [here](https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing).


### Summary
Please consider the changes I have proposed above and request another review when you are done making necessary corrections! I wish you the best with this and all other projects :100:

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by shshamim63** [comment]
## Status :red_circle: [!! Changes Required !!] :red_circle: 
___
Hi @kbjude and @paulo-techie :wave: ,
You have covered most of the task asked by the previous reviewer. Project contains readme, PR contains a summery, code looks neat and clean. But there are some issues that are blocking me to approve this project. I believe you guys will cover them easily. :muscle: 
___
#### Please follow the instructions to complete the project.
___
### :spades: [Mandatory Changes] :spades: 
___
1. It seems, stickler is not functional. Can you go through the process mentioned in this [link](https://github.com/microverseinc/linters-config/tree/master/css). Specially No 1. and 2.
image
2. The footer contains a set of links. Not a centered text. So please replace it with a set of links.
https://github.com/kbjude/design-tear-down/blob/2d15ecce44e62ea5af09467799a2e41f69e0f47b/index.html#L126-L135
___
#### Please fix the above mentioned issue and send a review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain

**Comment by kbjude** [comment]
Stickler installed and configured for linting on the repository

**Review by nikasulo — APPROVED** [review]
# Nice work with the changes!
Please merge and carry on! :smile: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Pull request merged**
